# Generated by Django 6.0.6 on 2026-07-04 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Ad')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug (ünvan)')),
                ('description', models.TextField(blank=True, verbose_name='Təsvir')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Kateqoriya',
                'verbose_name_plural': 'Kateqoriyalar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ad')),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True, verbose_name='Slug (ünvan)')),
                ('description', models.TextField(blank=True, verbose_name='Təsvir')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Qiymət (₼)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Şəkil')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stok (ədəd)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Satışdadır')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Ana səhifədə göstər')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='Kateqoriya')),
            ],
            options={
                'verbose_name': 'Məhsul',
                'verbose_name_plural': 'Məhsullar',
                'ordering': ['-created_at'],
            },
        ),
    ]
