# Generated by Django 6.0.6 on 2026-07-04 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-poçt')),
                ('subject', models.CharField(max_length=150, verbose_name='Mövzu')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Göndərilmə tarixi')),
                ('is_read', models.BooleanField(default=False, verbose_name='Oxunub')),
            ],
            options={
                'verbose_name': 'Əlaqə mesajı',
                'verbose_name_plural': 'Əlaqə mesajları',
                'ordering': ['-created_at'],
            },
        ),
    ]
