# Generated by Django 6.0.7 on 2026-07-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_email_to_phone'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_available', 'is_featured'], name='shop_produc_is_avai_d8a3db_idx'),
        ),
    ]
